# Generated by Django 4.2.2 on 2023-06-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionaldetail',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useradditionaldetail',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
