# Generated by Django 4.2.2 on 2023-06-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Delights', 'Food and Drinks'), ('Atmosphere', 'Ambiance and Decor'), ('Culinary', 'Chef and Kitchen'), ('Celebrations', 'Events and Special Occasions'), ('Alfresco', 'Outdoor Dining and Patio'), ('Hospitality', 'Team and Staff'), ('Capture', 'Dining Experience')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TastyTrov Gallery',
                'verbose_name_plural': 'TastyTrov Gallery',
                'ordering': ('-timestamp',),
            },
        ),
    ]
