# Generated by Django 4.2.2 on 2023-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='file',
            field=models.FileField(default='1.mp3', upload_to=''),
        ),
    ]
