# Generated by Django 4.2.2 on 2023-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_gallery_image_gallery_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
