# Generated by Django 4.2.2 on 2023-06-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_gallery_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
