# Generated by Django 4.2.2 on 2023-06-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gallery_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_description', models.CharField(blank=True, max_length=255, null=True)),
                ('meal_amount', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TastyTrov Menu',
                'verbose_name_plural': 'TastyTrov Menu',
                'ordering': ('meal_name',),
            },
        ),
    ]
