# Generated by Django 4.2.2 on 2023-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_menu_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
