# Generated by Django 4.2.2 on 2023-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_menu_meal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_description', models.CharField(blank=True, max_length=255, null=True)),
                ('meal_amount', models.FloatField()),
                ('estimated_time', models.CharField(choices=[('30 Minutes', '30 Minutes'), ('45 Minutes', '45 Minutes'), ('1 Hour', '1 Hour'), ('3 Hours', '3 Hours')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TastyTrov Menu',
                'verbose_name_plural': 'TastyTrov Menu',
                'ordering': ('meal_name',),
            },
        ),
    ]
