# Generated by Django 4.2.2 on 2023-06-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_offmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offmenu',
            options={'ordering': ('meal_name',), 'verbose_name': 'TastyTrov Off Menu', 'verbose_name_plural': 'TastyTrov Off Menu'},
        ),
    ]
