# Generated by Django 4.2.2 on 2023-07-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_offmenu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TastyTrovChef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_image', models.ImageField(upload_to='')),
                ('chef_first_name', models.CharField(max_length=255)),
                ('chef_last_name', models.CharField(max_length=255)),
                ('chef_bio', models.TextField()),
                ('chef_facebook_profile_link', models.URLField(blank=True, null=True)),
                ('chef_twitter_profile_link', models.URLField(blank=True, null=True)),
                ('chef_instagram_profile_link', models.URLField(blank=True, null=True)),
                ('chef_linkedin_profile_link', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasty Trov Chefs',
                'verbose_name_plural': 'Tasty Trov Chefs',
                'ordering': ('chef_first_name',),
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=255)),
                ('client_last_name', models.CharField(max_length=255)),
                ('testimonial', models.TextField(editable=False)),
                ('star_rating', models.IntegerField(editable=False)),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonials',
                'verbose_name_plural': 'Testimonials',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='WeeklyDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, unique=True)),
                ('meal_name', models.CharField(max_length=50)),
                ('meal_meta', models.CharField(blank=True, max_length=50, null=True)),
                ('meal_amount', models.FloatField()),
                ('meal_discount_amount', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weekly Deals',
                'verbose_name_plural': 'Weekly Deals',
                'ordering': ('deal_day',),
            },
        ),
    ]
