# Generated by Django 4.2.2 on 2023-07-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_tastytrovchef_testimonial_weeklydeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_social',
            field=models.URLField(blank=True, null=True),
        ),
    ]
