# Generated by Django 4.2.2 on 2023-07-09 22:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_gallery_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='file_type',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
